# Generated by Django 4.2.7 on 2023-11-05 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('short_description', models.CharField(blank=True, default='NA', max_length=200)),
                ('category', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, default='', upload_to='shop/images')),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('sub_category', models.CharField(default='', max_length=30)),
                ('description', models.CharField(blank=True, default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('phone_number', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, default='')),
                ('security_key', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
