# Generated by Django 4.2.7 on 2023-11-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitems',
            old_name='wishist',
            new_name='wishlist',
        ),
    ]
